### ISSUE TITLE
Just curious about how scalable this approach is?

### ISSUE THREAD

**Issue by sfabriece** [toymachiner62/hapi-authorization#14]
I'm working on a project and looking for authorization modules.

I want my servers to be near stateless. Do you think is is achievable with this module and if not any suggestions?

**Comment by toymachiner62** [comment]
Yes it is achievable. The way i was using it in one of my apps is I was authenticating a when they logged in and created a token and stored it in mongo along with other user details and then send that token back to the client after successful authentication. The client would then pass that token as a header on all requests to the server and before the server would do anything with the request it would check the token against mongo to ensure it was valid and hadn't expired.

**Comment by sfabriece** [comment]
Thanks for the answer.
