### ISSUE TITLE
Breaking change in 2.2.3 update from 2.2.2 - reverts to aclQuery siganture from 2.1.x

### ISSUE THREAD

**Issue by jancervinka** [toymachiner62/hapi-authorization#16]
I believe that you have an incorrect version in 2.2.3 tag. It contains the code of 2.1.x where aclQuery has a signature of `function(parameter, cb)`. So if you update from 2.2.x (where the signature is `function(parameter, request, cb)`) to 2.2.3, the code breaks.

**Comment by toymachiner62** [comment]
Can you point me to the function declaration you're specifically referring to?

**Comment by NicolasRitouet** [comment]
Indeed, the code contained in the 2.2.3 release seems to be old. The following line is not in the downloaded release:
https://github.com/toymachiner62/hapi-authorization/blob/master/lib/index.js#L41

**Comment by toymachiner62** [comment]
Ok i have no idea what I did to get myself screwed up that bad, but I think I have it working again with version 2.2.5. Please update from version 2.2.3 -> 2.2.5 and let me know if there's still any issues.
