### ISSUE TITLE
hapi-authorization is suppressing error messages

### ISSUE THREAD

**Issue by xkjyeah** [toymachiner62/hapi-authorization#17]
After activating hapi-authorization, error messages (usually from calling undefined functions and accessing undefined properties) are not thrown as errors.

This is highly annoying. I'll be submitting a pull request soon.

**Comment by xkjyeah** [comment]
But it's been fixed 10 days ago... alright

**Comment by leobudima** [comment]
I have the same problem with 3.0.2 and hapi 13.3.0. 

It's probably related to https://github.com/hapijs/hapi/issues/2771 , but same happens with useDomains set to false.
