### ISSUE TITLE
Need to fix failing test

### ISSUE THREAD

**Issue by toymachiner62** [toymachiner62/hapi-authorization#2]
I have no idea why this test fails. Need to figure it out.

https://github.com/toymachiner62/hapi-authorization/blob/hapi6%267/test/index.js#L86

**Comment by damonmcminn** [comment]
I've forked the repo to take this on.

**Comment by NicolasRitouet** [comment]
Seems to be solved?
https://github.com/toymachiner62/hapi-authorization/blob/master/test/index.js#L230

**Comment by toymachiner62** [comment]
I think you're right.
