### ISSUE TITLE
Support for Hapi v17

### ISSUE THREAD

**Issue by toddhickerson** [toymachiner62/hapi-authorization#24]
This plugin needs changes to the `register` method to support Hapi v17.

https://github.com/hapijs/hapi/issues/3658

**Comment by toddhickerson** [comment]
Hey @toymachiner62, are you still interested in maintaining this library? There are breaking changes in Hapi v17 that change the way plugins are handled, rendering this library unusable in Hapi v17. I'm looking for alternatives or will need to fork and update myself.

Lastly, are you looking for pull requests to fix this...and if so, will it be considered?

I really find the module useful and would hate to see it go away.

Thank you.

**Comment by toymachiner62** [comment]
Yes still interested in maintaining although I haven't used hapi.js in any
projects recently.

A pull request would really help me out.

Tom Caflisch
507.202.0087
TomCaflisch@gmail.com
http://allthingswebdesign.com

**Comment by NicolasRitouet** [comment]
I've started the work to migrate to hapi 17 on this branch:
https://github.com/mycsHQ/hapi-authorization/compare/master...hapi-17
Tests are not passing yet and `next()` have to been removed from the codebase.
I also removed `q`

**Comment by maxaus** [comment]
@NicolasRitouet Please, see my pull-request to your fork - I recently finished work on Hapi v17 related updates, but initially based on your branch. So it makes sence to merge my pull request to your repo (if it's ok), then make a pull request to this original repo.

**Comment by NicolasRitouet** [comment]
@maxaus thx a lot for your help 🎉
I've merged your PR into my branch. 👍🏻
I just got back from vacation, give me a few days to test it on my side and then create a PR to the original repo.

**Comment by heartstchr** [comment]
@NicolasRitouet  i am still getting `[1] "name" is required` is this repo supports hapi 17

**Comment by NicolasRitouet** [comment]
@toymachiner62 I've created the PR, but I had no time to test it properly. 😕
If someone can, you can just pull from the branch `hapi-17` from my fork (https://github.com/mycsHQ/hapi-authorization/tree/hapi-17).

**Comment by devinceble** [comment]
any news with the merge? my work around is using https://github.com/mycsHQ/hapi-authorization/tree/hapi-17-2 works with hapi v17.5.4 thanks @NicolasRitouet

**Comment by toymachiner62** [comment]
@devinceble Thanks for the nudge. I've got this into NPM as version 4.0.0 now. 

Also since i've not been using hapi.js the past couple years i'm way out of the loop with it. Any interest in any of you becoming a co-maintainer of this lib?
