### ISSUE TITLE
Multiple roles per user

### ISSUE THREAD

**Issue by JulianMayorga** [toymachiner62/hapi-authorization#5]
Hi there! Quick question: Is there a way to support multiple roles per user? If there is not, could you give me some pointers in order to implement that functionality? I would be happy to contribute.

Cheers!

**Comment by toymachiner62** [comment]
You should be able to set multiple roles for a user already and when using hapi-authorization it should check to see that any of the roles a user has are in the authorized roles.

If this is not the case please let me know.
